[project]
name = "transform"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adlfs>=2024.12.0",
    "dbt-core>=1.9.8",
    "dbt-duckdb>=1.9.3",
    "fsspec>=2025.5.1",
]
