name: dbt run and test

on: workflow_dispatch

env:
  DBT_ENV_SECRET_STORAGE_ACCOUNT_NAME_PROD: ${{ secrets.DBT_ENV_SECRET_STORAGE_ACCOUNT_NAME_PROD }}
  DBT_ENV_SECRET_STORAGE_ACCOUNT_KEY_PROD: ${{ secrets.DBT_ENV_SECRET_STORAGE_ACCOUNT_KEY_PROD }}

jobs:
  run-dbt-project:
    name: Run dbt Project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/transform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: dbt-run
        id: dbt-run
        uses: mwhitaker/dbt-action@v1.7.3
        with:
          # dbt_command: "dbt run --target prod --profiles-dir ."
          dbt_command: "dbt run --target prod"
          # dbt_project_folder: "src/transform"

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-run.outputs.result }}"
        shell: bash
