name: dbt run and test

on: workflow_dispatch

env:
  DBT_ENV_SECRET_STORAGE_ACCOUNT_NAME_PROD: ${{ secrets.DBT_ENV_SECRET_STORAGE_ACCOUNT_NAME_PROD }}
  DBT_ENV_SECRET_STORAGE_ACCOUNT_KEY_PROD: ${{ secrets.DBT_ENV_SECRET_STORAGE_ACCOUNT_KEY_PROD }}

jobs:
  run-dbt-project:
    name: Run dbt Project
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/transform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Set up Python and install dependencies
        run: |
          uv python install
          uv venv .venv
          source .venv/bin/activate
          uv sync --locked

      - name: Debug Path
        run: |
          source .venv/bin/activate
          echo $PATH
          which dbt

      - name: Run dbt
        run: |
          source .venv/bin/activate
          dbt run --target prod

      - name: Run dbt tests
        run: |
          source .venv/bin/activate
          dbt test --target prod
        # id: dbt-run
        # uses: mwhitaker/dbt-action@v1.7.3
        # with:
        # dbt_command: "dbt run --target prod --profiles-dir ."
        # dbt_command: "dbt run --target prod"
        # dbt_project_folder: "src/transform"

      # - name: Get the result
      #if: ${{ always() }}
      # run: echo "${{ steps.dbt-run.outputs.result }}"
      # shell: bash
