name: Run dbt in production

on: workflow_dispatch

env:
  DBT_ENV_SECRET_STORAGE_ACCOUNT_NAME_PROD: ${{ secrets.DBT_ENV_SECRET_STORAGE_ACCOUNT_NAME_PROD }}
  DBT_ENV_SECRET_STORAGE_ACCOUNT_KEY_PROD: ${{ secrets.DBT_ENV_SECRET_STORAGE_ACCOUNT_KEY_PROD }}

jobs:
  run-dbt-project:
    name: Run dbt Project
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/transform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Set up Python and install dependencies
        run: |
          uv python install
          uv venv .venv
          source .venv/bin/activate
          uv sync --locked

      - name: Run dbt
        id: dbt_run
        run: |
          source .venv/bin/activate
          dbt run --target prod
