name: Build and Push Docker Images

on:
  push:
    tags:
      - "extract*"
env:
  REGISTRY: ghcr.io
  EXTRACT_IMAGE_NAME: ${{ github.repository_owner }}/extract-app

jobs:
  build-and-push-extract:
    name: Build and Push Extract
    runs-on: ubuntu-latest
    # Only run for backend tags
    if: contains(github.ref, 'extract')

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/extract
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.EXTRACT_IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
            ${{ env.REGISTRY }}/${{ env.EXTRACT_IMAGE_NAME }}:latest
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
      app: extract
